### ISSUE TITLE
[BUG] OOM Issue

### ISSUE THREAD

**Issue by JarcauCristian** [h2oai/h2o-llmstudio#311]
### 🐛 Bug

I am trying to run your application and I have run it using and NVIDIA A100 with 40GB of VRAM and every time I get OOM error and I can get it to work. If you can help me with this.

**Comment by maxjeblick** [comment]
Could you share the configuration of the experiment(s) that failed?
Also, can you run H2O LLM Studio with default settings? The default settings should work with a 40GB GPU (or even with a smaller card).

**Comment by JarcauCristian** [comment]
Thank you for the quick response! I ran the LLM Studio with the default settings I didn't change anything, I just followed the steps on the github page. I also attached the configuration that I used for the experiment.
[config.txt](https://github.com/h2oai/h2o-llmstudio/files/12161862/config.txt)

**Comment by JarcauCristian** [comment]
My bad, I use still using the Compiled Model turned on. It seems to be working now. Thank you very much!

**Comment by psinger** [comment]
great!
